function [fitresult, gof] = biexp(tau1, Z)
%CREATEFIT(TAU1,Z)
%  Create a fit.
%
%  Data for 'EXP_bi' fit:
%      X Input : tau1
%      Y Output: Z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Mar-2023 14:50:06


%% Fit: 'EXP_bi'.
[xData, yData] = prepareCurveData( tau1, Z );

% Set up fittype and options.
ft = fittype( 'a*exp(-x/b)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 ];
opts.MaxFunEvals = 5000;
opts.Robust = 'Bisquare';
opts.StartPoint = [0.711768743274231 10 ];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'EXP_mono' );
h = plot( fitresult, xData, yData );
legend( h, 'Z vs. tau1', 'EXP_mono', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'tau1', 'Interpreter', 'none' );
ylabel( 'Z', 'Interpreter', 'none' );
grid on


