function [fitresult, gof] = T1_SR_mono(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'T1_SR_mono' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-May-2024 14:16:53


%% Fit: 'T1_IR_mono'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a*(1-exp(-x/T1))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0];
opts.Robust = 'Bisquare';
opts.StartPoint = [0.5 0.5];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'T1_IR_mono' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'T1_IR_mono', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


